name: publish to Modrinth and CurseForge
on:
  [ workflow_dispatch ]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: extract short_version from gradle.properties
        id: get-short-version
        run: |
          value=$(grep '^short_version=' gradle.properties | cut -d'=' -f2)
          echo "short_version=$value"
          echo "short_version=$value" >> $GITHUB_ENV

      - name: publish to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: MGHiBUyJ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1015414
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: Etherology ${{ env.short_version }}
          changelog-file: CHANGELOG.*
          version-type: beta
          game-versions: |
            1.21
            1.21.1